export const THEME = {
  COLOR: {
    LOGIN_TITLE: "#212529",
    INPUT_BORDER: "#429008",
    INPUT_BORDER_HOVER: "#53B50A",
    INPUT_TEXT_COLOR: "#2E2E2E",
    BUTTON_LOGIN_DARK_GRADIENT: "#112C50",
    BUTTON_LOGIN_DARK_GRADIENT_HOVER: "#112C50",
    BUTTON_LOGIN_LIGHT_GRADIENT: "rgba(38, 153, 162, 1)",
    BUTTON_LOGIN_LIGHT_GRADIENT_HOVER: "#2699A2",
    LOGIN_BUTTON_TEXT: "#fff",
    LOADER: "#fff",
  },
  BACKGROUND: {
    MAIN: "#f4efef",
    LOADER: "rgba(0,0,0,.5)",
  },
};
